### ISSUE TITLE
expect(xxx).to.not.have.been.called

### ISSUE THREAD

**Issue by kikito** [lightsofapollo/sinon-mocha#3]
Is it possible? I could not find a way to do it. I'm trying to test stuff like this:

```
var f = sinon.spy(obj, 'f');

doSomething();

expect(f).to.not.have.been.called;

doSomethingElse();

expect(f).to.have.been.called;
```

**Comment by lightsofapollo** [comment]
I originally wrote sinon-mocha to work with this: https://github.com/lightsofapollo/sinon-expect
The only thing in this repo is a automatic teardown of sinon mocks/spies...

**Comment by kikito** [comment]
Oh I see. Wrong repo. My apologies. Closing down this issue.
